ssh_keys: 
- "{{lookup('file', './ssh_keys/drtom')}}"

# not point in using  ntp for a virtual machine
ntp_enabled: False

# comes handy, however can be a big security hole 
nrepl_bind_address: 0.0.0.0
