ssh_keys: 
- "{{lookup('file', './ssh_keys/drtom')}}"
- "{{lookup('file', './ssh_keys/mfa')}}"
- "{{lookup('file', './ssh_keys/nimaai')}}"
- "{{lookup('file', './ssh_keys/rca')}}"

removed_ssh_keys: []

ntp_server: ntp.zhdk.ch
lein_service_xmx_value: 1G 
user_interface_xmx_value: 4G

