### clone repo ################################################################

- name: Create target dir 
  file: path=/var/local/cider-ci
        owner=root
        group=root
        state=directory
        mode=0755

- stat: path=/var/local/cider-ci/.git
  register: cider_ci_git_dir_stat 

- shell: cd  /var/local/cider-ci && git remote set-url origin {{cider_ci_repo}} 
  changed_when: False
  when: cider_ci_git_dir_stat.stat.exists

- name: Git clone or update project
  git:  
    repo: "{{cider_ci_repo}}"
    accept_hostkey: true
    dest: /var/local/cider-ci
    version: "{{cider_ci_git_ref}}"
    force: yes

- shell: cd /var/local/cider-ci && git submodule sync --recursive && git submodule update --init --recursive
