
- hosts: zhdk
  roles:
  - role: add-ssh-keys

###############################################################################
### Release Compat Check ######################################################
###############################################################################


- hosts: all

  vars_files: 
    - releases.yml

  vars:
    release: "{{releases[0]}}"
    git_ref: "{{release.git_ref}}"


  roles:
    - role: compatibility


###############################################################################
### Http Basic Auth Shared Secret #############################################
###############################################################################


- hosts: cider-ci-server

  tags: [basic-auth-secret,user-interface,trial-manager,respository-manager,storage-manager,executor-service]

  tasks: 

    - file: path=/etc/cider-ci 
            state=directory
            mode=0700

    - shell:  head -c 20 /dev/urandom | hexdump -e '"%x"' > /etc/cider-ci/basic-auth-secret.txt
              creates=/etc/cider-ci/basic-auth-secret.txt

    - shell : "cat /etc/cider-ci/basic-auth-secret.txt"
      register: basic_auth_secret_task
      changed_when: False

    - file: path=/etc/cider-ci/basic-auth-secret.txt
            mode=0700

#   - debug: var=basic_auth_secret_task

    - set_fact: basic_auth_secret={{basic_auth_secret_task.stdout}}

    - debug: var=basic_auth_secret


- hosts: cider-ci-executors
  tags: [basic-auth-secret]
  tasks: 
    #  - debug: msg={{hostvars['ci-server']['basic_auth_secret']}}


- hosts: all

  tasks: 
  - apt:  upgrade=dist
          update_cache=yes 
          cache_valid_time=3600


###############################################################################
### Executors #################################################################
###############################################################################


- hosts: cider-ci-executors
  vars_files: 
    - releases.yml
    - vars-executors.yml

  vars:
    release: "{{releases[0]}}"
    git_ref: "{{release.git_ref}}"



#  tasks: 
#    - debug: msg="'{{release}}'"
#      tags: [debug]
  roles: 
    - role: debuntu-setup
    - role: executor-packages 
    - role: executor-chromedriver
    - role: executor-phantomjs

    - role: postgresql

    - role: executor-mariadb
    - role: jdk-leiningen

    - role: executor-user
      user: '{{executor_execution_user}}'
      tags: [executor-user]

    - role: executor-service-remove-pre-1.5
      tags: [remove-old]

    - role: lein-git-service
      lein_git_service_name: executor
      lein_git_service_git_repo: "https://github.com/cider-ci/cider-ci_executor.git"
      lein_git_service_user: root
      tags: [executor-service]

#   - role: executor-service
#     tags: [executor-service]

    - role: rbenv
      user: '{{executor_execution_user}}'

    - role: rbenv-ruby 
      user: '{{executor_execution_user}}'
      ruby: '{{rubies.mri}}'

    - role: rbenv-ruby 
      user: '{{executor_execution_user}}'
      ruby: '{{rubies.jruby}}'

#    - role: postgresql
#      version: 9.2
#      port: 5432




###############################################################################
### Server ####################################################################
###############################################################################



- hosts: cider-ci-server

  vars_files: 
    - releases.yml
    - vars-server.yml

  vars:
    release: "{{releases[0]}}"
    git_ref: "{{release.git_ref}}"

#  tasks: 
#   - debug: msg="'{{release}}'"
#     tags: [debug]

  roles: 

    - role: debuntu-setup

    - role: postgresql
      version: 9.3
      port: 5433

    - role: message-broker

    - role: jdk-leiningen

    - role: server-polyglot-remove


#    - role: server-polyglot-user

      ruby: '{{rubies.jruby}}'

    - role: server-apache2
      tags: [apache2,apache]

    - role: server-reverse-proxy
      tags: [reverse-proxy]

    - role: server-common
      tags: [server-common]

    - role: user-interface
      tags: [user-interface]


#    - role: server-polyglot-as 
#    - role: server-im
#    - role: server-tb
#    - role: server-polyglot-as-restart

    - role: lein-git-service
      lein_git_service_name: repository-manager
      lein_git_service_git_repo: "https://github.com/cider-ci/cider-ci_repository-manager.git"
      tags: [repository-manager]

    - role: lein-git-service
      lein_git_service_name: trial-manager
      lein_git_service_git_repo: "https://github.com/cider-ci/cider-ci_trial-manager.git"
      tags: [trial-manager]

    - role: lein-git-service
      lein_git_service_name: storage-manager
      lein_git_service_git_repo: "https://github.com/cider-ci/cider-ci_storage-manager.git"
      tags: [storage-manager]


###############################################################################
###############################################################################
###############################################################################




- hosts: all
  tags: [debug]

  vars_files: 
    - releases.yml

  vars:
    release: "{{releases[0]}}"
    git_ref: "{{release.git_ref}}"

  roles:
    - role: update-version-info
    
