### Release compat check, upgrade, shared secrets #############################
- hosts: all
  vars_files: 
    - releases.yml
    - vars.yml
    - "{{ vars_local | default('vars.yml') }}"

  tasks: 

    - shell: pidof /bin/systemd
      register: has_systemd
      ignore_errors: yes

    - fail: msg="Debian/Wheezy must use systemd" 
      when: ansible_distribution_release == 'wheezy' and has_systemd.stdout != "1"

    - apt_repository: repo='deb http://ftp.debian.org/debian wheezy-backports main' state=present update_cache=yes
      #apt_repository: repo='deb http://ftp.debian.org/debian wheezy-backports main contrib non-free' state=present update_cache=yes
      when: ansible_distribution_release == 'wheezy'

    - apt: upgrade=yes update_cache=yes cache_valid_time=3600

#    - debug: var=vars_local
#      tags: [debug]


  roles:
    - role: compatibility
    - role: debuntu-setup
    - role: shared-secrets
      tags: 
        - api
        - basic-auth-secret
        - builder
        - dispatcher
        - executor-service
        - executor-user
        - rabbitmq
        - repository
        - storage
        - user-interface

### Executors #################################################################
- hosts: cider-ci-executors
  vars_files: 
    - releases.yml
    - vars.yml
    - vars-executors.yml
    - "{{ vars_local | default('vars.yml') }}"

  vars:
    release: "{{releases[0]}}"
    git_ref: "{{release.git_ref}}"
    lein_git_service_restart: true

  roles: 
    - role: executor-packages 
    - role: executor-chrome
      tags: "chrome"
    - role: executor-chromedriver
    - role: executor-phantomjs

    - role: postgresql
      postgresql_version: 9.3
      present: false
      
    - role: postgresql
      postgresql_version: 9.4

    - role: executor-mariadb
      tags: [ mysql ]

    - role: jdk-leiningen

    - role: executor-user
      user: '{{executor_execution_user}}'
      tags: [executor-user, user-interface]

    - role: lein-git-service
      lein_git_service_user: "{{executor_service_user}}"
      lein_git_service_name: cider-ci_executor
      lein_git_service_git_repo: "{{cider_ci_executor_git_repo}}" 
      tags: [executor-service]

    - role: rbenv
      user: '{{executor_execution_user}}'

    - role: rbenv-ruby 
      user: '{{executor_execution_user}}'
      ruby: '{{rubies.mri}}'

    - role: rbenv-ruby 
      user: '{{executor_execution_user}}'
      ruby: '{{rubies.jruby}}'


### Server ####################################################################
- hosts: cider-ci-server
  vars_files: 
    - releases.yml
    - vars.yml
    - vars-server.yml
    - "{{ vars_local | default('vars.yml') }}"

  vars:
    release: "{{releases[0]}}"
    git_ref: "{{release.git_ref}}"
    lein_git_service_restart: true

  roles: 

    - role: server-secrets
      tags: 
        - api
        - basic-auth-secret
        - repository
        - storage
        - dispatcher
        - user-interface

    - role: postgresql
      postgresql_version: 9.3
      present: false
      
    - role: postgresql
      postgresql_version: 9.4
      port: 5432

    - role: rabbitmq
      tags: [rabbitmq]

    - role: jdk-leiningen

    - role: server-polyglot-remove

      ruby: '{{rubies.jruby}}'

    - role: server-apache2
      tags: [apache2,apache]

    - role: server-reverse-proxy
      tags: [reverse-proxy]

    - role: server-common
      tags: [server-common]

    - role: user-interface
      tags: [user-interface]

    - role: lein-git-service
      lein_git_service_name: cider-ci_repository
      lein_git_service_git_repo: "{{cider_ci_repository_git_repo}}" 
      tags: [repository]

    - role: lein-git-service
      lein_git_service_name: cider-ci_dispatcher
      lein_git_service_git_repo: "{{cider_ci_dispatcher_git_repo}}"
      tags: [dispatcher]

    - role: lein-git-service
      lein_git_service_name: cider-ci_builder
      lein_git_service_git_repo: "{{cider_ci_builder_git_repo}}"
      tags: [builder]

    - role: lein-git-service
      lein_git_service_name: cider-ci_storage
      lein_git_service_git_repo: "{{cider_ci_storage_git_repo}}"
      tags: [storage]

    - role: lein-git-service
      lein_git_service_name: cider-ci_api-v2
      lein_git_service_git_repo: "{{cider_ci_api_git_repo}}"
      tags: [api]


#### update version info ######################################################
- hosts: all

  vars_files: 
    - releases.yml

  vars:
    release: "{{releases[0]}}"
    git_ref: "{{release.git_ref}}"

  roles:
    - role: update-version-info
    
