- hosts: cider-ci-server

  vars_files: 
    - releases.yml
    - vars.yml
    - vars-server.yml

  roles: 
    - role: server-secrets


  tasks: 

    - name: Dump database
      shell: 'pg_dump -v -x -F c 
              -f /tmp/cider-ci_production_dump.pgbin 
              {{database.name}}'

    - fetch: src=/tmp/cider-ci_production_dump.pgbin 
             dest=tmp
