
- hosts: zhdk
  roles:
  - role: add-ssh-keys

- hosts: all


  vars_files: 
    - releases.yml

  vars:
    release: "{{releases[0]}}"
    git_ref: "{{release.git_ref}}"


  roles:
    - role: compatibility



###############################################################################
### Executors #################################################################
###############################################################################


- hosts: cider-ci-executors
  vars_files: 
    - releases.yml
    - vars-executors.yml

  vars:
    release: "{{releases[0]}}"
    git_ref: "{{release.git_ref}}"



#  tasks: 
#    - debug: msg="'{{release}}'"
#      tags: [debug]
  roles: 
    - role: debuntu-setup
    - role: executor-packages 
    - role: executor-chromedriver
    - role: executor-phantomjs

    - role: postgresql

    - role: executor-mariadb
    - role: jdk-leiningen

    - role: executor-user
      user: '{{executor_service_user}}'
      tags: [executor-user]

    - role: executor-service
      tags: [executor-service]

    - role: rbenv
      user: '{{executor_service_user}}'

    - role: rbenv-ruby 
      user: '{{executor_service_user}}'
      ruby: '{{rubies.mri}}'

    - role: rbenv-ruby 
      user: '{{executor_service_user}}'
      ruby: '{{rubies.jruby}}'

#    - role: postgresql
#      version: 9.2
#      port: 5432




###############################################################################
### Server ####################################################################
###############################################################################



- hosts: cider-ci-server

  vars_files: 
    - releases.yml
    - vars-server.yml

  vars:
    release: "{{releases[0]}}"
    git_ref: "{{release.git_ref}}"

#  tasks: 
#   - debug: msg="'{{release}}'"
#     tags: [debug]

  roles: 

    - role: debuntu-setup

    - role: postgresql
      version: 9.3
      port: 5433

    - role: message-broker

    - role: jdk-leiningen

    - role: server-polyglot-remove


#    - role: server-polyglot-user

      ruby: '{{rubies.jruby}}'

    - role: server-apache2

    - role: server-reverse-proxy
      tags: [reverse-proxy]

    - role: server-common
      tags: [server-common]

    - role: user-interface
      tags: [user-interface]


#    - role: server-polyglot-as 
#    - role: server-im
#    - role: server-tb
#    - role: server-polyglot-as-restart

    - role: lein-git-service
      lein_git_service_name: repository-manager
      lein_git_service_git_repo: "https://github.com/cider-ci/cider-ci_repository-manager.git"
      tags: [repository-manager]

    - role: lein-git-service
      lein_git_service_name: trial-manager
      lein_git_service_git_repo: "https://github.com/cider-ci/cider-ci_trial-manager.git"
      tags: [trial-manager]

    - role: lein-git-service
      lein_git_service_name: storage-manager
      lein_git_service_git_repo: "https://github.com/cider-ci/cider-ci_storage-manager.git"
      tags: [storage-manager]


###############################################################################
###############################################################################
###############################################################################




- hosts: all
  tags: [debug]

  vars_files: 
    - releases.yml

  vars:
    release: "{{releases[0]}}"
    git_ref: "{{release.git_ref}}"

  roles:
    - role: update-version-info
    
