# Ansible managed 

release: 
  version_major: "{{release.version_major}}"
  version_minor: "{{release.version_minor}}"
  version_patch: "{{release.version_patch}}" 
  version_pre:  "{{release.version_pre}}"
  version_build: "{{release.version_build}}"

git:
  repositories_path: "{{repositories_path}}"

trial_attachments_http_prefix: /cider-ci/storage/trial-attachments

http_server:
  host: "{{web_host_ip}}"
  port: 80
  ssl: false

messaging: 

  connection: 
    vhost: cider-ci
    username: guest
    password: guest
    host: 127.0.0.1

  default_message_expiration: 1

  exchanges:
    - name: branch_event_topic
      type: topic
      durable: true


