# clean services and configuration 

- shell: |
    rm -rf /etc/ansible
    rm -rf /etc/init/cider-ci*
    rm -rf /etc/systemd/system/cider-ci*
    rm -rf /etc/cider-ci*
    rm -rf /usr/local/bin/cider-ci*


# restart will stop all of our now removed services

- command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- local_action: wait_for host={{ inventory_hostname }}
                port=22
                delay=1
                timeout=60
                state=started
  ignore_errors: true
  sudo: false

# clean all the rest: logfiles, code 

- shell: |
    rm -rf /var/local/cider-ci* 
    rm -rf /var/log/cider-ci/*

