- apt: pkg={{item}} state=latest update_cache=yes cache_valid_time=3600
  with_items: [python-httplib2]

- set_fact: api_password={{api_password}}
- set_fact: api_username={{api_username}}
- set_fact: server_host={{hostvars[groups['cider-ci-server'][0]]['server_host']}}
- set_fact: secret_key_base={{hostvars[groups['cider-ci-server'][0]]['secret_key_base']}}

- uri:
    url: https://{{server_host}}/cider-ci/ui/configuration_management_backdoor/invoke
    user: system_admin
    password: "{{secret_key_base}}"
    force_basic_auth: yes
    body: |
      User.find_or_create_by(login: '{{api_username}}').update_attributes!(password: '{{api_password}}')
    method: POST
    "HEADER_Content-Type": application/ruby
    register: update_or_create_user

- template: >
    src=cider_ci_api
    dest=~{{user}}/.bash_login.d/cider_ci_api
    owner={{user}}
    mode=0755

- lineinfile:
    line: "{{item}},"
    dest: /etc/cider-ci/traits.txt
    create: yes
    state: present
  with_items:
    - cider-ci_api-access
