- name: Create target dir 
  file: path={{executor_service_app_dir}}
        state=directory
        mode=0755


- name: Git clone or update project
  git:  repo=https://github.com/cider-ci/cider-ci_executor.git
        dest={{executor_service_app_dir}}
        version=wip
        update=yes
  register: update_executor_service 
  changed_when: update_executor_service.before != update_executor_service.after


- name: create target dir
  file: path={{executor_service_app_dir}}/target
        state=directory
        mode=0755
        owner={{executor_service_user}}
  when: update_executor_service.changed

- template: src=logrotate
            dest=/etc/logrotate.d/{{executor_service_name}}

- file: path={{executor_service_working_dir}}
        state=directory
        mode=0755
        owner={{executor_service_user}}

- file: path={{executor_service_repository_dir}}
        state=directory
        mode=0755
        owner={{executor_service_user}}

- template: src=conf.yml
            dest={{executor_service_app_dir}}/conf.yml
  register: executor_service_config

- template: src=init.conf
            dest=/etc/init/{{executor_service_name}}.conf
  register: executor_service_init

- service: name={{executor_service_name}} state=restarted
  when: executor_service_config.changed or executor_service_init.changed

- copy: src=reboot dest=/etc/cron.daily/ZZZ-reboot mode=0755
