- template: src=env
            dest=~{{executor_execution_user}}/.bash_login.d/firefox-esr-env
            owner={{executor_execution_user}}
            mode=0755

- lineinfile:
    line: "{{item}},"
    dest: /etc/cider-ci/traits.txt
    create: yes
    state: present
  with_items:
    - firefox-esr
