database: 
  adapter: "postgresql" 
  classname: "org.postgresl.Driver"
  subname: '//localhost:{{database.port}}/{{database.name}}'
  subprotocol: "postgresql"
  user: "{{database.user}}"
  password: "{{database.password}}"
  max_pool_size: 3

hostname: "{{web_host_name | default(ansible_default_ipv4.address) }}"

secret: "{{secret_key_base}}"

basic_auth:
  username: service
  password: "{{services_basic_auth_secret}}"

session:
  secret: "{{secret_key_base}}"

messaging: 
  connection: 
    vhost: cider-ci
    host: 127.0.0.1
    username: cider-ci
    password: "{{cider_ci_rabbitmq_secret}}" 


server_base_url: "https://{{web_host_name | default(hostvars[groups['cider-ci-server'][0]]['ansible_default_ipv4']['address']) }}"

services: 

  api: 

    http: 
      host: localhost
      port: 8885
      context: /cider-ci
      sub_context: /api
      ssl: false

    nrepl:
      port: 7885
      bind: "{{nrepl_bind_address | default('127.0.0.1')}}"
      enabled: true

    database: 
      max_pool_size: 10

  builder: 

    http: 
      host: 127.0.0.1
      port: 8884
      context: /cider-ci
      sub_context: /builder
      ssl: false

    nrepl: 
      port: 7884
      bind: "{{nrepl_bind_address | default('127.0.0.1')}}"
      enabled: true

    database: 
      max_pool_size: 10


  dispatcher: 

    http: 
      host: "127.0.0.1"
      port: 8882
      context: '/cider-ci'
      sub_context: '/dispatcher'
      ssl: false

    nrepl:
      port: 7882
      bind: "{{nrepl_bind_address | default('127.0.0.1')}}"
      enabled: true

    database: 
      max_pool_size: 30

  repository: 

    http: 
      host: 127.0.0.1
      port: 8881
      context: /cider-ci
      sub_context: /repositories
      ssl: false

    nrepl:
      port: 7881
      bind: "{{nrepl_bind_address | default('127.0.0.1')}}"
      enabled: true

    database: 
      max_pool_size: 20

    repositories: 
      path: "./tmp/repositories" 


  storage: 

    http: 
      host: localhost
      port: 8886
      context: /cider-ci
      sub_context: /storage
      ssl: false

    nrepl:
      port: 7886
      bind: "{{nrepl_bind_address | default('127.0.0.1')}}"
      enabled: true

    database: 
      max_pool_size: 10

    stores: 

      - url_path_prefix: "/trial-attachments"
        retention_time_days: 10
        file_path: "{{trial_attachments_path}}"
        db_table: trial_attachments

      - url_path_prefix: "/tree-attachments"
        retention_time_days: 90
        file_path: "{{tree_attachments_path}}"
        db_table: tree_attachments


  ui: 

    http: 
      host: localhost
      port: 8880
      context: /cider-ci
      sub_context: /ui
      ssl: false


# configuration for the reverse proxy for dev and test, not used in production
reverse_proxy:

  http: 
    host: localhost
    port: 8888
    ssl: false

  nrepl:
    port: 7888
    bind: "127.0.0.1"
    enabled: true


