- set_fact: restart=False

- name: Install dependencies
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: 
    - nodejs

- name: Create target dir 
  file: path={{ui_root_path}}
        owner=user-interface
        group=user-interface
        state=directory
        mode=0755

- shell: cd {{ui_root_path}} && git remote set-url origin {{user_interface_git_repo}}
  changed_when: False

- name: Git clone or update project
  git:  repo={{user_interface_git_repo}}
        accept_hostkey=yes
        dest={{ui_root_path}}
        version={{git_ref}}
        update=yes
  register: git_clone_or_update

- shell: cd {{ui_root_path}} && git submodule init && git submodule update
  when: git_clone_or_update.changed
  # somehow submodules get not set properly on update 

- debug: var=git_clone_or_update

- file: path={{ui_root_path}} 
        owner=user-interface 
        group=user-interface 
        recurse=true
  changed_when: false

- set_fact: restart=True
  when: git_clone_or_update.changed 

### Bundle #####################################################################

- name: Bundle Jruby
  shell: su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
          && rbenv-load 
          && cd {{ui_root_path}}
          && export RAILS_ENV={{rails_env}} 
          && export RBENV_VERSION={{rubies.jruby.version}} 
          && bundle install --deployment' user-interface 
         executable=/bin/bash
  register: bundle_jruby
  changed_when: bundle_jruby.stdout | match(".*Installing.*")


- name: Bundle MRI
  shell: su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
          && rbenv-load 
          && cd {{ui_root_path}}
          && export RAILS_ENV={{rails_env}} 
          && export RBENV_VERSION={{rubies.mri.version}} 
          && bundle install --deployment' user-interface 
         executable=/bin/bash
  register: bundle_mri
  changed_when: bundle_mri.stdout | match(".*Installing.*")


### Settings ##################################################################

- template: src=settings.yml
            dest={{ui_root_path}}/config/settings.local.yml
  register: settings

- set_fact: restart=True
  when: settings.changed 


### Secret ####################################################################

- template: src=secrets.yml
            dest={{ui_root_path}}/config/secrets.yml
            owner=user-interface
            group=user-interface
            mode=0600
  register: secret

- set_fact: restart=True
  when: secret.changed 


### Database ##################################################################

- name: Configure database
  template: src=database.yml
            dest={{ui_root_path}}/config/database.yml
            owner=user-interface
            mode=0755
  register: database_config 

- name: Migrate
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd {{ui_root_path}}
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{rubies.mri.version}} 
            && bundle exec rake db:create db:migrate' user-interface
          executable=/bin/bash
  register: migrate
  changed_when: not migrate.stdout | match("")

- set_fact: restart=True
  when: database_config.changed 

### Seed 

- template: src=seeds.rb
             dest={{ui_root_path}}/db/seeds.rb
             owner=user-interface
  register: seedfile

- shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd {{ui_root_path}}
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{rubies.mri.version}} 
            && bundle exec rake db:seed' user-interface 
          executable=/bin/bash
  register: seed
  changed_when: false

#- debug: var=seed


### Assets ####################################################################

- name: Precompile assets 
  shell:  su -l -s /bin/bash -c 'source /etc/profile.d/rbenv-load.sh 
            && rbenv-load 
            && cd {{ui_root_path}}
            && export RAILS_ENV={{rails_env}} 
            && export RBENV_VERSION={{rubies.mri.version}} 
            && rm -rf public/assets/*
            && rm -rf tmp/cache/*
            && bundle exec rake assets:precompile' user-interface
          executable=/bin/bash
  register: precompile_assets
  changed_when: not precompile_assets.stderr | match("")

### Service ###################################################################


- template: src=user-interface.conf
            dest=/etc/init/user-interface.conf 
  register: init_script

- set_fact: restart=True
  when: init_script.changed 


- template: src=background-processor.conf
            dest=/etc/init/background-processor.conf 
  register: init_script

- set_fact: restart=True
  when: init_script.changed 


- service:  name=user-interface
            state=restarted
  when: restart

- service:  name=user-interface
            state=started

- service:  name=background-processor
            state=restarted
  when: restart

- service:  name=background-processor
            state=started

