### Maria db

- apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

- apt_repository:  repo="deb http://mirror2.hs-esslingen.de/mariadb/repo/5.5/debian wheezy main"
                   state=present
  when: ansible_distribution_release == 'wheezy'

- apt_repository:  repo="deb http://mirror2.hs-esslingen.de/mariadb/repo/5.5/debian wheezy main"
                   state=absent 
  when: ansible_distribution_release != 'wheezy'

- apt_repository: repo='deb http://mirror2.hs-esslingen.de/mariadb/repo/5.5/ubuntu trusty main'
  when: ansible_distribution_release != 'wheezy'


- apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: 
    - mariadb-client-5.5
    - mariadb-server-5.5
    - libmariadbclient-dev
    - python-mysqldb
    - python-configparser

- mysql_user: name={{executor_execution_user}}
              password={{executor_execution_user}}
              priv=*.*:ALL 
              state=present

- template: src=mysql_env
            dest=~{{executor_execution_user}}/.bash_login.d/mysql_env
            owner={{executor_execution_user}}
            mode=0755

- lineinfile:
    line: "{{item}},"
    dest: /etc/cider-ci/traits.txt
    create: yes
    state: present
  with_items:
    - mariadb
    - mysql

