### load rbenv

- template: src=load_rbenv
            dest="~{{user}}/.bash_login.d/load_rbenv"
            owner={{user}} group={{user}} mode=0755

- lineinfile:
    line: "{{item}},"
    dest: /etc/cider-ci/traits.txt
    create: yes
    state: present
  with_items:
    - rbenv
