- apt: pkg=apg state=present update_cache=yes cache_valid_time=3600

- file: path={{secrets_dir_path}}
        state=directory
        mode=0700

- shell: >
    umask -S u=rw,g=,o=  && apg -M NLC -x 40 -m 40 -n 1  > {{services_basic_auth_secret_path}}
    creates={{services_basic_auth_secret_path}}

- shell: cat {{services_basic_auth_secret_path}}
  register: services_basic_auth_secret_task
  changed_when: False

- set_fact: services_basic_auth_secret={{services_basic_auth_secret_task.stdout}}
